# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' [[Rcpp::export]]
#' @name cbind_rcpp
#' @title cbind_rcpp
#' @description Esta fución une un vector y una matriz siempre y cuando el largo
#' del vector sea igual a la candidad de filas que tiene la matriz.
#' @param A es una matriz numerica de dimención nxm
#' @param B es un vector de largo n
#' @return matriz con los datos del vector insertados en una nueva columna
#' @examples
#' matriz <- matrix(round(runif(9, 1, 10)), nrow = 3, ncol = 3)
#' vector <- c(1:3)
#' set.seed(123)
#' result <- cbind_rcpp(matriz,vector)
#' result
#' @export
NULL

#' [[Rcpp::export]]
#' @name mMatrix_rcpp
#' @title mMatrix_rcpp
#' @description Esta funcion ejecuta la multipliacion de dos matrices
#' @param A es una matriz numerica de dimención nxm
#' @param B es una matriz numerica de dimención mxm
#' @return regresa una matriz resultante de la multipliacion
#' @examples
#' A <- matrix(round(runif(9, 1, 10)), nrow = 3, ncol = 3)
#' V <- matrix(round(runif(9, 1, 10)), nrow = 3, ncol = 3)
#' set.seed(123)
#' result <- mMatrix_rcpp(A,B)
#' result
#' @export
NULL

#' [[Rcpp::export]]
#' @name maxMin_cpp
#' @title maxMin_cpp
#' @description Esta funcion se encarga de buscar el maximo de los minimos de ambas matrices
#' para devolver una matriz diferente con los valores encontrados.
#' @param A es una matriz numerica de dimención nxn
#' @param B es una matriz numerica de dimención nxn
#' @return regresa una matriz numerica de dimencion nxn
#' @examples
#' A <- matrix(round(runif(n, min = 0, max = 1), 1), nrow = 3, ncol = 3)
#' B <- matrix(round(runif(n, min = 0, max = 1), 1), nrow = 3, ncol = 3)
#' diag(A) <- 1
#' diag(B) <- 1
#' set.seed(123)
#' result <- maxMin_cpp(A,B)
#' result
#' @export
NULL

#' [[Rcpp::export]]
#' @name rbind_rcpp
#' @title rbind_rcpp
#' @description Esta fución une un vector y una matriz siempre y cuando el largo
#' del vector sea igual a la candidad de columnas que tiene la matriz.
#' @param A es una matriz numerica de dimención nxm
#' @param B es un vector de largo m
#' @return matriz con los datos del vector insertados en una nueva fila
#' @examples
#' matriz <- matrix(round(runif(9, 1, 10)), nrow = 3, ncol = 3)
#' vector <- c(1:3)
#' set.seed(123)
#' result <- rbind_rcpp(matriz,vector)
#' result
#' @export
NULL

#' [[Rcpp::export]]
#' @name whichMax
#' @title whichMax
#' @description Esta funcion devuelve un data.frame en donde se encuentran las 
#' coordenadas de los valores maximos ubicados dentro de la matriz.
#' @param A es una matriz numerica de dimención nxm
#' @return retorna un data.frame
#' @examples
#' matriz <- matrix(round(runif(9, 1, 10)), nrow = 3, ncol = 3)
#' set.seed(123)
#' result <- whichMax(matriz)
#' result
#' @export
NULL

#' [[Rcpp::export]]
#' @name whichMin
#' @title whichMin
#' @description Esta funcion devuelve un data.frame en donde se encuentran las 
#' coordenadas de los valores minimos ubicados dentro de la matriz.
#' @param A es una matriz numerica de dimención nxm
#' @return retorna un data.frame
#' @examples
#' matriz <- matrix(round(runif(9, 1, 10)), nrow = 3, ncol = 3)
#' set.seed(123)
#' result <- whichMin(matriz)
#' result
#' @export
NULL

