# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbind_rcpp <- function(A, B) {
    .Call(`_Mtrixpro_cbind_rcpp`, A, B)
}

mMatrix_rcpp <- function(A, B) {
    .Call(`_Mtrixpro_mMatrix_rcpp`, A, B)
}

maxMin_cpp <- function(matrixA, matrixB) {
    .Call(`_Mtrixpro_maxMin_cpp`, matrixA, matrixB)
}

rbind_rcpp <- function(A, B) {
    .Call(`_Mtrixpro_rbind_rcpp`, A, B)
}

whichMax <- function(matrix_A) {
    .Call(`_Mtrixpro_whichMax`, matrix_A)
}

whichMin <- function(matrix_A) {
    .Call(`_Mtrixpro_whichMin`, matrix_A)
}

